#cloud-config
# Snippet de cloud-init para instalar Docker

package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - vim
  - htop

runcmd:
  # Instalar Docker
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

  # Instalar Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }

final_message: "Docker instalado correctamente. Sistema listo para usar."
