#cloud-config
# Snippet para preparar nodos de Kubernetes

package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  # Deshabilitar swap
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # Cargar módulos del kernel
  - modprobe overlay
  - modprobe br_netfilter

  # Configurar sysctl
  - sysctl -w net.bridge.bridge-nf-call-iptables=1
  - sysctl -w net.bridge.bridge-nf-call-ip6tables=1
  - sysctl -w net.ipv4.ip_forward=1

  # Instalar containerd
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y containerd.io

  # Configurar containerd
  - mkdir -p /etc/containerd
  - containerd config default | tee /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

final_message: "Nodo preparado para Kubernetes. Ejecutar kubeadm para continuar."
